openapi: "3.0.3"
info:
  title: Ping API
  version: "1.0.0"
paths:
  /ping:
    get:
      summary: Retourne "pong"
      response:
        '200':
        description: OK
        constent:
          text/plain:
            schema:
              type: string
              example: "pong"
