openapi: 3.0.3
  info:
    title: User Management API
    version: 1.0.0
    description: An API for managing users with pagination parameters.
  servers:
    - url: http://localhost:8000
  paths:
    /users:
      get:
        summary: Retrieve a list of users
        description: Fetches a paginated list of users based on page and size query parameters.
        parameters:
          - name: page
            in: query
            description: The page number to retrieve (default is 1).
            schema:
              type: integer
              default: 1
            required: false
          - name: size
            in: query
            description: The number of users per page (default is 20).
            schema:
              type: integer
              default: 20
            required: false
        responses:
          '200':
            description: A list of users
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
                example:
                  - id: 1
                    name: "Alice"
                    email: "alice@example.com"
          '400':
            description: Bad request due to invalid parameter types
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                example:
                  error: "Bad types for provided query parameters"
  components:
    schemas:
      User:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          email:
            type: string
      Error:
        type: object
        properties:
          error:
            type: string